version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: thoughtflow_frontend
    ports:
      - "8081:8081"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}

  backend:
    build:
      context: ./backend
    container_name: thoughtflow_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}

  db:
    build:
      context: ./database
    container_name: thoughtflow_journal_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: