version: '3.8'

services:
  db:
    build: .
    container_name: thoughtflow_journal_db
    environment:
      MYSQL_ROOT_PASSWORD: Camelwides9864!
      MYSQL_DATABASE: journal_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: